src/openearth/apps/processing/urls.py
from django.conf.urls import patterns, include, url
import views

env_patterns = patterns(
    '',
    url(r'jobs/$', views.JobListView.as_view(), name='jobs'),
    url(r'repo/$', views.RepoRevisionsView.as_view(), name='repo_revisions'),
    url(r'scripts/$', views.ScriptsView.as_view(), name='scripts'),
    url(r'scripts/(?P<script>.+)$', views.ScriptRevisionsView.as_view(), name='script_revisions'),
    url(r'open_earth_revisions/(?P<extension>.*)$', views.OpenEarthRevisionsView.as_view(), name='open_earth_revisions'),
    url(r'job/create/$', views.JobCreateView.as_view(), name='job_create'),
    url(r'job/(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/$', views.JobDetailView.as_view(), name='job_detail'),
    url(r'job/(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/edit/$', views.JobUpdateView.as_view(), name='job_update'),
)

urlpatterns = patterns(
    '',
    url(r'^$', views.EnvironmentListView.as_view(), name='environment'),
    url(r'^create/$', views.EnvironmentCreateView.as_view(), name='environment_create'),
    url(r'^(?P<pk>\d+)/$', views.EnvironmentDetailView.as_view(), name='environment_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.EnvironmentUpdateView.as_view(), name='environment_update'),
    url(r'^(?P<env>\d+)/', include(env_patterns)),
)

src/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from openearth import views
from openearth.apps.kmlserver.views import ListDirView
from libs.auth import LDAPSetPasswordForm, LDAPPasswordChangeForm, LDAPPasswordResetForm
from ws4redis.wsgi_server import WebsocketWSGIServer
from apps.script_execution_manager.wsgi_server import patched_call
import logging


logger = logging.getLogger(__name__)

#TODO Find a better location to pacth WebsocketWSGIServer.__call__
logger.debug('Patching "ws4redis.wsgi_server.WebsocketWSGIServer.__call__"...')
WebsocketWSGIServer.__call__ = patched_call

admin.autodiscover()

urlpatterns = patterns(
    '',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^kmlserver/', include('openearth.apps.kmlserver.urls')),
    url(r'^documentation', include('openearth.apps.documentation.urls')),
    url(r'^tags_input/', include('tags_input.urls', namespace='tags_input')),
    url(r'^', include('openearth.urls')),
    url(r'^', include('cms.urls')),
    url(r'^', include('filer.server.urls')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^smedia/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.FILER_STORAGES['private']['main']['OPTIONS']['location'],
        }),
        # url(r'^kml/(?P<path>.*)$', 'django.views.static.serve', {
        #     'document_root': settings.FILER_STORAGES['private']['kml']['OPTIONS']['location'],
        #     'show_indexes': True
        # }),
   )

src/openearth/apps/processing/models.py
from __future__ import unicode_literals
import urlparse
from celery.result import AsyncResult
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings
from django.utils import timezone
from django_extensions.db.fields import PostgreSQLUUIDField
from filer.fields.file import FilerFileField
from openearth.apps.script_execution_manager.tasks import commit
from django.utils.functional import lazy
from openearth.libs import svn
from django.core import exceptions
import reversion


def get_revisions(url, username, password, limit=100, revision=None,
                  format=False):
    revisions = svn.revisions(
        url=url,
        username=username,
        password=password,
        limit=limit,
        revision=revision)

    if format:
        formatted = []
        for revision in revisions:
            formatted.append((
                int(revision['@revision']),
                '[%(@revision)s] %(msg)s @ %(date)s by %(author)s' % revision,
            ))

        return tuple(formatted)
    else:
        return revisions


def get_open_earth_python_revisions(limit=100, revision=None, format=False):
    return get_revisions(
        url=settings.OPEN_EARTH_TOOLS_PYTHON_URL,
        username=settings.OPEN_EARTH_TOOLS_PYTHON_USERNAME,
        password=settings.OPEN_EARTH_TOOLS_PYTHON_PASSWORD,
        limit=limit,
        revision=revision,
        format=format,
    )


def get_open_earth_matlab_revisions(limit=100, revision=None, format=False):
    return get_revisions(
        url=settings.OPEN_EARTH_TOOLS_MATLAB_URL,
        username=settings.OPEN_EARTH_TOOLS_MATLAB_USERNAME,
        password=settings.OPEN_EARTH_TOOLS_MATLAB_PASSWORD,
        limit=limit,
        revision=revision,
        format=format,
    )


def get_open_earth_revisions(limit=100, revision=None, format=False):
    return get_revisions(
        url=settings.OPEN_EARTH_TOOLS_URL,
        username=settings.OPEN_EARTH_TOOLS_USERNAME,
        password=settings.OPEN_EARTH_TOOLS_PASSWORD,
        limit=limit,
        revision=revision,
        format=format,
    )


class Extension(models.Model):
    name = models.CharField(max_length=255)
    extension = models.CharField(max_length=32, unique=True)

    def get_name(self):
        return self.name or self.extension

    def __repr__(self):
        return '<%s[%s]%s>' % (
            self.__class__.__name__,
            self.extension,
            self.name or '',
        )

    def __unicode__(self):
        return unicode(self.get_name())


@reversion.register
class ProcessingJobImage(models.Model):
    interpreter = models.CharField(
        _('interpreter'), max_length=255,
        help_text=_('e.g /opt/python2.7/bin/python'))
    libvirt_image = models.FilePathField(
        _('image'), path=settings.CONTAINER['base_dir'])
    name = models.CharField(
        _('name'), max_length=255, help_text=_('e.g python 2.7'))
    description = models.TextField(_('description'), help_text=_(
        'describe which libraries are available in this environment'))
    extensions = models.ManyToManyField(Extension, blank=True)

    def __unicode__(self):
        try:
            return u'%s' % self.name
        except AttributeError:
            return '%s[%d]' % (self.__class__.__name__, self.id)

    class Meta:
        verbose_name = _('libvirt image')
        verbose_name_plural = _('libvirt images')


class ProcessingEnvironmentManager(models.Manager):
    def author(self, author):
        return super(ProcessingEnvironmentManager,
                     self).get_queryset().filter(author=author)


@reversion.register
class ProcessingEnvironment(models.Model):
    class REPOS:
        SVN = getattr(settings, "ENVIRONMENT_SVN_SETTINGS", None)

    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    libvirt_image = models.ForeignKey(
        ProcessingJobImage, verbose_name=_('processing environment'),
        help_text=_('The environment required for your processing script.'))
    repo = models.CharField(_('relative SVN repo url'), max_length=255, help_text=_('The relative position of the svn repo folder containing your [raw/] and [scripts/] directories. The root of the svn repository is: {0}').format(REPOS.SVN['url']))
    name = models.CharField(_('name'), max_length=50, blank=False, null=False, help_text=_('A custom name for your environment.'))
    open_earth = models.BooleanField(_('use OpenEarth tools'), default=False, help_text=_('Enable this if your script needs OpenEarth tools for processing the raw data.'))
    created_date = models.DateTimeField(_('date created'), default=timezone.now)

    objects = ProcessingEnvironmentManager()

    @property
    def jobs(self):
        return self.processing_environment.all().filter(environment=self.id)

    def __unicode__(self):

        try:
            return u'%s' % self.name
        except AttributeError:
            return '%s[%d]' % (self.__class__.__name__, self.id)

    def get_absolute_url(self):
        return reverse('environment_detail', kwargs={'pk': self.pk})

    def get_repo_url(self):
        return '{0}{1}'.format(self.REPOS.SVN['url'], self.repo)

    def invalid_repo(self):
        try:
            self.get_repo_revisions()
        except svn.SvnRepoDoesNotExist, e:
            return e

    def get_revisions(self, url, limit=100, revision=None, format=False):
        return get_revisions(
            url=url,
            username=self.REPOS.SVN['username'],
            password=self.REPOS.SVN['password'],
            limit=limit,
            revision=revision,
            format=format,
        )

    def get_repo_revisions(self, limit=100, revision=None, format=True):
        return self.get_revisions(self.get_repo_url(), limit, revision, format)

    def get_scripts_url(self):
        return self.get_repo_url() + self.REPOS.SVN['scripts']

    def get_script_revisions(self, script, limit=10, revision=None,
                             format=True):
        return self.get_revisions(self.get_scripts_url(), limit,
                                  revision, format)

    def get_script_choices(self, for_choices=False):
        output, err = svn.list_(
            url=self.get_scripts_url(),
            username=self.REPOS.SVN['username'],
            password=self.REPOS.SVN['password'])

        # Get the supported extensions for this image
        extensions = tuple(self.libvirt_image.extensions.values_list(
            'extension', flat=True)) or ('.py', '.m')

        scripts = tuple(s for s in output if s.endswith(extensions))

        if for_choices:
            scripts = tuple((s, s) for s in scripts)
        return scripts

    class Meta:
        verbose_name = _('processing environment')
        verbose_name_plural = _('processing environments')
        ordering = ['-created_date']


@reversion.register
class ProcessingJob(models.Model):
    class STATUS(object):
        CREATED = 10
        SCHEDULED = 20
        PENDING = 30
        STARTED = 40
        RUNNING = 50
        FINISHED = 100
        REVOKED = 500
        FAILURE = 999

        choices = [
            (CREATED, _('Created')),
            (SCHEDULED, _('Scheduled')),
            (PENDING, _('Pending')),
            (STARTED, _('Started')),
            (RUNNING, _('Running')),
            (FINISHED, _('Finished successfully')),
            (REVOKED, _('Revoked')),
            (FAILURE, _('Failed')),
        ]

    uuid = PostgreSQLUUIDField(primary_key=True)
    environment = models.ForeignKey(ProcessingEnvironment,
                                    verbose_name=_('processing environment'),
                                    related_name='processing_environment',
                                    on_delete=models.SET_NULL,
                                    null=True, blank=True,)

    start = models.DateTimeField(_('start job after '), default=timezone.now)
    created_date = models.DateTimeField(_('date created'),
                                        default=timezone.now)
    status = models.PositiveIntegerField(_('status'),
                                         default=STATUS.CREATED,
                                         choices=STATUS.choices,
                                         null=True, blank=True)
    auto_commit = models.BooleanField(_('Commit automatically'), default=True)
    script = models.CharField(_('script name'), max_length=255,
                              choices=[(1, 'error')])
    script_revision = models.PositiveIntegerField(
        help_text='Override the script revision, defaults to "revision"',
        null=True, blank=True, choices=[('', '')])
    revision = models.PositiveIntegerField(
        help_text='Execute the data (and scripts) from this revision',
        null=True, blank=True, choices=[('', 'Latest')])
    open_earth_revision = models.PositiveIntegerField(
        help_text='Execute with specific open earth version',
        null=True, blank=True)

    def get_script_revisions(self, limit=10, revision=None, format=True):
        return self.environment.get_revisions(self.get_script_url(False),
                                              limit, revision, format)

    def get_repo_revisions(self, limit=100, revision=None, format=True):
        return self.environment.get_repo_revisions(limit, revision, format)

    def __init__(self, *args, **kwargs):
        super(ProcessingJob, self).__init__(*args, **kwargs)
        self._meta.get_field_by_name('script')[0]._choices = lazy(
            self.get_script_choices, tuple)()
        self._meta.get_field_by_name('script_revision')[0]._choices = lazy(
            self.get_script_revisions, tuple)()
        self._meta.get_field_by_name('revision')[0]._choices = lazy(
            self.get_repo_revisions, tuple)()

    def get_script_choices(self):
        return self.environment.get_script_choices(for_choices=True)

    @property

src/openearth/apps/processing/templates/environment_base.html
{% load i18n %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{{ title|title }}{{ object.name|title }}</h1>
        {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ message }}
            </div>
        {% endfor %}
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <form action="" method="post">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="pull-right">
                        <input class="btn btn-primary btn-xs" type="submit" name="submit" value="{% trans "Save" %}">
                    </span>
                    {% trans 'Settings' %}
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                            {% csrf_token %}
                            <table class="table table-hover">
                                {% include "forms/as_table.html" %}
                            </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
                <div class="panel-footer">
                </div>
                <!-- /.panel-footer -->
            </div>
            <!-- /.panel -->
        </form>
    </div>

</div>
<!-- /.row -->

src/openearth/apps/processing/templates/environment_create.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Create" %}
{% endblock %}

{% block content %}
    {% include "environment_base.html" with title=_('Create') %}
{% endblock %}

src/openearth/apps/processing/templates/environment_update.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Update" %}
{% endblock %}

{% block content %}
    {% include "environment_base.html" %}
{% endblock %}


{% block extra-bottom-slot %}

{% endblock %}

src/openearth/apps/processing/templates/job_create.html
{% extends "base.html" %}
{% load i18n l10n %}

{% block title %}
    {% trans "New job" %}
{% endblock %}

{% block content %}
    {% include "job_base.html" with title=_('New job') %}
{% endblock %}

{% block extra-bottom-slot %}
    {# if we have a form this means that the svn repo is valid #}
    {% if form %}
        <script>
            (function ($) {
                var scripts_url = '{% url "scripts" env=view.kwargs.env %}';

                function fetchScriptRevisions() {
                    $.getJSON(scripts_url + $(this).val(), function (data) {
                        var select = $('#id_script_revision');
                        var option = select.children()[0];
                        select.empty().append(option);
                        $.each(data, function (i, revision) {
                            select.append($('<option>').attr('value', revision[0]).text(revision[1]));
                        });
                    });
                }

                $('#id_script').change(fetchScriptRevisions).change();

                // Opening accordion based on URL
                var url = document.location.toString();
                if (url.match('#')) {
                    $('#' + url.split('#')[1]).collapse('show');
                }

                /* Bootstrapify the forms */
                $('form input, form select').addClass('form-control');
                $('form select').css('width', '100%').select2();

                $('#id_open_earth_revision').select2({
                    placeholder: {
                        id: '',
                        text: 'Latest revision',
                    },
                    ajax: {
                        url: '{% url "open_earth_revisions" env=view.kwargs.env extension='' %}',
                        dataType: 'json',
                        delay: 250,
                        data: function(params){
                            console.log('data', arguments);
                            return {
                                revision: params.revision,
                            };
                        },
                        processResults: function (data, params) {
                            if(data){
                                params.revision = data[data.length-1]['@revision'];
                            }else{
                                params.revision = '';
                            }

                            return {
                                results: data,
                                pagination: {
                                    more: data.length >= 100
                                }
                            };
                        },
                    },
                    escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
                    templateResult: function(object){
                        if(!object || !object['@revision'])return 'Loading...';

                        var markup = '<div class="clearfix">' +
                            '<strong>' + object.author + ':</strong> ' +
                            (object.msg || '') +
                            '<br>' + 
                            '<small>' +
                                '<strong>' + object['@revision'] + '</strong> ' +
                                object.date +
                            '</small>' +
                            '</div>';
                        return markup;
                    },
                    templateSelection: function(object){
                        if(object.text)return object.text;

                        return '[' + object['@revision'] + '] ' +
                            object.msg + ' @ ' +
                            object.date + ' by ' +
                            object.author;
                    },
                });

            })(jQuery);
        </script>
    {% endif %}
{% endblock %}

src/openearth/apps/processing/templates/job_detail.html
{% extends "base.html" %}
{% load i18n l10n static %}

{% block title %}
    {% trans "Detail" %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{% trans "Job details" %}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    {% trans "Details" %}
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table class="table table-hover" id="job-detail-table">
                        <tr>
                            <th class="col-sm-3"><label class="control-label" for="">{% trans "Environment" %}</label></th>
                            <td class="col-sm-9"><a
                                    href="{% url 'environment_detail' object.environment.id %}">{{ object.environment|title }}</a>
                            </td>
                        </tr>
                         <tr>
                            <th class="col-sm-3"><label class="control-label" for="">{% trans "Script" %}</label></th>
                            <td class="col-sm-9">{{ object.environment.get_repo_url }}scripts/{{ object.script }}</td>
                        </tr>
                        <tr>
                            <th class="col-sm-3"><label class="control-label" for="">{% trans "UUID" %}</label></th>
                            <td class="col-sm-9">{{ object.uuid }}</td>
                        </tr>
                        <tr>
                            <th class="col-sm-3"><label class="control-label" for="">{% trans "Status" %}</label></th>
                            <td class="col-sm-9" id="job-status-field">{{ object.get_status_display|title }}</td>
                        </tr>
                        <tr>
                            <th class="col-sm-3"><label class="control-label" for="">{% trans "Scheduled start" %}</label></th>
                            <td class="col-sm-9">{{ object.start|date:"d-m-Y H:i:s" }}</td>
                        </tr>
                        <tr>
                            <th class="col-sm-3"><label class="control-label" for="">{% trans "Created" %}</label></th>
                            <td class="col-sm-9">{{ object.created_date|date:"d-m-Y H:i:s" }}</td>
                        </tr>
                        <tr>
                            <th class="col-sm-3"><label class="control-label" for="">{% trans "Auto Commit" %}</label></th>
                            <td class="col-sm-9">{{ object.auto_commit|yesno }}</td>
                        </tr>
                        <tr style="display: none">
                            <th>{% trans 'Progress' %}</th>
                            <td>
                                <div class="progress">
                                    <div class="progress-bar" id="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0"
                                         aria-valuemax="100" style="width: 0;">
                                    </div>
                                </div>
                                <p class="help-block" id="progress-bar-message"></p>
                            </td>
                        </tr>
                    </table>
                    <button type="button" class="btn btn-primary"
                            id="preform-job-action"
                            data-job-id="{{ object.uuid }}"
                            data-env-id="{{ object.environment.id }}"
                            data-action="stop_job" {% if object.status >= 100 %}disabled{% endif %}>
                        {% if object.status <= 100 %}
                            {% trans 'revoke job' %}
                        {% else %}
                            {% trans 'oops' %}
                        {% endif %}
                    </button>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>

    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="checkbox pull-right" style="margin:4px 0">
                        <label>
                            <input id="cb_scrolldown_first" class="cb_scrolldown" type="checkbox"> Scroll down
                        </label>
                    </div>
                    <span class="fa-stack">
                      <i class="fa fa-square fa-stack-2x"></i>
                      <i class="fa fa-terminal fa-stack-1x fa-inverse"></i>
                    </span>
                    {% trans "Processing" %}
                    <div class="clearfix"></div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <ul class="nav nav-tabs nav-justified">
                        <li class="{% if not object.results %}active{% endif %}"><a href="#terminal-tab" data-toggle="tab">Log</a>
                        </li>
                        <li class="{% if object.results %}active{% endif %}"><a href="#results-tab" data-toggle="tab">Results</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade {% if not object.results %}active in{% endif %}" id="terminal-tab"><pre id="terminal" data-ws-url="{{ ws_url }}"></pre></div>
                        <div class="tab-pane fade {% if object.results %}active in{% endif %}" id="results-tab">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{% trans "Filename" %}</th>
                                        <th>{% trans "Committed ?" %}</th>
                                        <th>{% trans "Sha1 Hash" %}</th>
                                        <th>&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for result in object.processing_result.all %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td><a href="{{ result.file.url }}">{{ result.file }}</a></td>
                                        <td>{{ result.committed|yesno }}</td>
                                        <td>{{ result.file.sha1 }}</td>
                                        <td><a href="{{ result.file.url }}" title="{% trans "Download" %}"><i class="fa fa-download fa-fw"></i></a></td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="3">{% trans 'No results found' %}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- /.panel-body -->
                <div class="panel-footer">
                    <div class="checkbox pull-right" style="margin:4px 0">
                        <label>
                            <input class="cb_scrolldown" type="checkbox"> Scroll down
                        </label>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <!-- /.panel-footer -->
            </div>
            <!-- /.panel -->
        </div>

    </div>
    <!-- /.row -->
{% endblock %}

{% block extra-bottom-slot %}
    <script src="{% static "js/processing.js" %}"></script>
{% endblock %}

src/openearth/apps/processing/templates/job_list_row.html
{% load i18n %}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                {% trans 'Jobs' %}
                <span class="pull-right">
                    {% if environment.id %}
                    <a href="{% url 'job_create' environment.id %}" class="btn btn-primary btn-xs" role="button">
                        <i class="fa fa-plus"></i> {% trans 'New job' %}
                    </a>
                    {% endif %}
                </span>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>{% trans 'Planned start' %}</th>
                                <th>{% trans 'Auto commit' %}</th>
                                <th>{% trans 'Script' %}</th>
                                <th>{% trans 'Status' %}</th>
                                <th>{% trans 'Created date' %}</th>
                                <th>{% trans 'Uuid' %}</th>
                                <!-- <th>&nbsp;</th> -->
                            </tr>
                        </thead>
                        <tbody>
                            {% for job in object_list %}
                                <tr onclick="javascript:window.location.href='{% url 'job_detail' env=job.environment.id uuid=job.uuid %}';" style="cursor:pointer;">
                                    <td>{{ job.start|date:"d-m-Y H:i:s" }}</td>
                                    <td>{{ job.auto_commit|yesno }}</td>
                                    <td>{{ job.script }}</td>
                                    <td>{{ job.get_status_display }}</td>
                                    <td>{{ job.created_date|date:"d-m-Y H:i:s" }}</td>
                                    <td>{{ job.uuid }}</td>
                                    <!-- <td>
                                        {% if job.status < 100 %}
                                        <a href="{% url 'job_detail' env=job.environment.id uuid=job.uuid %}" title="{% trans "View" %}"><i class="fa fa-tasks fa-fw"></i></a>
                                        <a href="{% url 'job_update' env=job.environment.id uuid=job.uuid %}" title="{% trans "Edit" %}"><i class="fa fa-pencil-square-o fa-fw"></i></a>
                                        {% else %}
                                            <a href="{% url 'job_detail' env=job.environment.id uuid=job.uuid %}" title="{% trans "View" %}"><i class="fa fa-tasks fa-fw"></i></a>
                                        {% endif %}
                                    </td> -->
                                 </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="6">{% trans 'No jobs defined' %}</td>
                                </tr>
                            {% endfor %}

                             <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{%  url 'environment_detail' environment.id %}?page={{ page_obj.previous_page_number }}">previous</a>
                                    {% endif %}
                                    <span class="page-current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{%  url 'environment_detail' environment.id  %}?page={{ page_obj.next_page_number }}">next</a>
                                    {% endif %}
                                </span>
                            </div>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>

</div>
<!-- /.row -->